<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> PHP EXERCISES</title>
</head>
<body>
    <h4>My Exercises</h4>
    <ul>
        <li><a href="intro.php">Introduce yourself</a></li>
        <li><a href="simplemath.php">Simple Math</a></li>
        <li><a href="Area and Perimeter of a Rectangle.php">Area and Perimeter of a Rectangle</a></li>
        <li><a href="Swapping Variables.php">Swapping Variables</a></li>
        <li><a href="Salary Calculator.php">Salary Calculator</a></li>
        <li><a href="BMI Calculator.php">BMI Calculator</a></li>
        <li><a href="String Manipulation.php">String Manipulation</a></li>
        <li><a href="Bank Account Simulation.php">Bank Account Simulation</a></li>
        <li><a href="Simple Grading System.php">Simple Grading System</a></li>
        <li><a href="Currency Converter.php">Currency Converter</a></li>
        <li><a href="Travel Cost Estimator.php">Travel Cost Estimator</a></li>


    </ul>
</body>
</html>
